### ISSUE TITLE
Breakpoint not set correctly (debug mode)

### ISSUE THREAD

**Issue by moserthemoserian** [X16Community/x16-emulator#113]
When setting a breakpoint in debug mode, the BRK field is not setting the correct value.  It appears to be 3 bytes instead of 2.  Verified that this is not happening with R42.

**For example:**
1. Entered debugger, view instructions at 080D `d80d`
2. Pressed `F9` to set breakpoint
3. BRK field is set to `00080D` instead of expected `080D` and does not break at the desired location.
_Assume that it's setting the breakpoint at 0008 instead of 080D_

**Comment by gaekwad** [comment]
Could you try with the newest build of the emulator? I think this is the bug that was just fixed. Thanks.

**Comment by moserthemoserian** [comment]
yup, sorry about that I was using a download didn't see the revisions.  all good!
