### ISSUE TITLE
PCM Empty flag not being set correctly.

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-emulator#126]
I dont think the empty flag on AUDIO_CTRL is being set when the PCM fifo is empty.

Take the attached test application. Using vblank it writes 0x70 to the PCM buffer a set number of times. This means you'll only ever hear a noise if the fifo is empty. (As in this case a 0 is used, hence a 'click' would be heard.)

You can change the number of values per vblank that are entered using the + and - keys.

The PCM is set to 8bit mono with a playback rate of 32, so 1/4 speed.

The display shows the status of the FULL, AFLOW and EMPTY flags. The EMPTY and AFLOW flags is updated first in the interrupt before data is entered, and the FULL flag is checked after.

You can see that we need to enter around 205/206 (0xcd/0xce) values per frame to have no clicks. However as you reduce the number of entries per frame, a noise is quickly heard yet the EMPTY flag isn't set. The empty flag only starts appearing with 169/0xa9 values entered per frame.

Maybe the empty flag connected to audio buffer, not the PCM FIFO?

[pcmtest.zip](https://github.com/X16Community/x16-emulator/files/11929402/pcmtest.zip)

Source is included in the zip if needed.

Note: Not tested on actual hardware, so that would be worth doing.

**Comment by akumanatt** [comment]
Box16 emulates this correctly. I think it's something to do with #116 which I forgot to mark it as draft before someone merged it. This should've been reverted until that feature is confirmed on hardware (which I don't plan to look into it until after FX update is fully merged).

**Comment by Yazwh0** [comment]
I'm testing vs R43.
