### ISSUE TITLE
PSG signal generation has the wrong resolution

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-emulator#158]
Looking at the VERA PSG code, the signals appear to be 6 bits
![image](https://github.com/X16Community/x16-emulator/assets/90315107/c891b36e-6575-450d-bb3d-34d9e6957e74)

The emulator appears to use 10bits
![image](https://github.com/X16Community/x16-emulator/assets/90315107/1b7f4259-23ac-417f-87e8-00c7c1177679)

Looks like it was 10bits at somepoint, but was reverted in the VERA code, but not the emulator.
![image](https://github.com/X16Community/x16-emulator/assets/90315107/f32f6285-68d2-4eec-a3a2-2373e850d2b5)

**Comment by mooinglemur** [comment]
Resolved by #167
