### ISSUE TITLE
Add option to warp while loading code and then slow down to normal speed afterward

### ISSUE THREAD

**Issue by markjreed** [X16Community/x16-emulator#164]
I think this used to be automatic and then changed because of #33, but it would be useful to be able to turn that behavior back on with an option, like `-warpload` or some such, especially for long .bas files.

**Comment by mooinglemur** [comment]
#33 addressed the fact that loads were not instantaneous, but the logic expected them to be, so the emulator thought it was behind *after* the load.  It didn't slow down loads.
