### ISSUE TITLE
Certain (?) Joypads on macs can crash the emulator on startup

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-emulator#178]
Not an issue that I've seen personally, but was on Discord.

https://discord.com/channels/547559626024157184/547563183762571264/1165329040438214716

**Comment by mooinglemur** [comment]
This is probably beyond anything that can be investigated reasonably.  It looks like it happened on one person's machine, probably in SDL, so not necessarily something we can do anything about.  If it comes up again we can open/reopen something.
