### ISSUE TITLE
Can't set window location, fullscreen changes all monitors on Windows

### ISSUE THREAD

**Issue by hstubbs3** [X16Community/x16-emulator#183]
Working on older Windows 10 laptop - laptop screen is 1366x768, secondary monitor is 1920x1080
Trying to launch x16emu from cmd on secondary monitor with scale=2 opens the emulator on my main screen with the Windows bar off the top of the screen... Since alt+space is captured by the app, can't access the 'move' option in the dropdown... 

Tried fullscreen but it sets resolution on both monitors.. 

at minimum the app should ensure that its menu bar is visible or provide some shortcut key to allow moving/scaling options.
Possibly just make the app remember where it was last opened or add maximized/scaled view options... 

I did come up with workaround so I can keep working for now..put these files in folder with x16emu.exe and use cxrun instead of x16emu (assuming x16emu.exe is already on Windows Path) 

cxrun.bat - 
- - - - - - 
start python3 C:\Users\hstub\git\CommanderX16\x16emu\mvwindow.py
x16emu -debug -rtc %

mvwindow.py
- - - - - - - - - 
import ctypes
import sys
from time import sleep

EnumWindows = ctypes.windll.user32.EnumWindows
EnumWindowsProc = ctypes.WINFUNCTYPE(ctypes.c_bool, ctypes.POINTER(ctypes.c_int), ctypes.POINTER(ctypes.c_int))
GetWindowText = ctypes.windll.user32.GetWindowTextW
GetWindowTextLength = ctypes.windll.user32.GetWindowTextLengthW
IsWindowVisible = ctypes.windll.user32.IsWindowVisible
MoveWindow = ctypes.windll.user32.MoveWindow

tries = 30
def foreach_window(hwnd, lParam):
	global tries
	if IsWindowVisible(hwnd):
		length = GetWindowTextLength(hwnd)
		buff = ctypes.create_unicode_buffer(length + 1)
		GetWindowText(hwnd, buff, length + 1)
		title = buff.value
		if title.startswith(u'Commander X16'):
			print(f'found window called {title}')
			MoveWindow(hwnd, 1600, 0, 1000, 1000, True)
			tries=0
	return True

while tries:
	tries -= 1
	sleep(1)
	EnumWindows(EnumWindowsProc(foreach_window), 0)
	print(f'tries left {tries}')

**Comment by irmen** [comment]
The `-fullscreen` is the maximized option though?   Weird that on windows it changes both monitors, this is not the case on Linux for example. Maybe there's something in SDL we should tweak.

I agree that it would be nice to avoid having a screen scale that is too large to actually fit on your monitor - maybe it's possible to check this and instead revert to "a maximized window" instead if this is the case - so that the window title and borders remain visible.

**Comment by mooinglemur** [comment]
Alt+Space works for me unless the emulator is in capture mode (Ctrl+M).
