### ISSUE TITLE
Forked projects do not run the build action

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-emulator#213]
Some error to do with the readme.pdf.

Can't imagine its too important.

![image](https://github.com/X16Community/x16-emulator/assets/90315107/e550549e-4d08-4dc1-99e7-593215eccdf9)

**Comment by mooinglemur** [comment]
This is strange.  I had a problem last week which had similar results within my own repo, and I think it happened to be a transient GitHub problem.  It went away a half day later.

Can you try causing an actions build in your own fork again? I'm wondering if it was a GitHub problem at that particular point in time.

**Comment by mooinglemur** [comment]
Unable to reproduce.  It seems like a transient problem with GitHub at that point in time.  If you continue to have this problem, please reopen.
