### ISSUE TITLE
Graceful handling of Rockwell instructons

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-emulator#218]
This topic is mostly a place for discussion and input RE emulator handling of the Rockwell instructions.

The specific instructions are: BBS0-BBS7, BBR0-BBR7, RMB0-RMB7, and SMB0-SMB7. They are easy to identify: if an opcode ends in 7 or F, it's one of these groups. These are collectively known as the **Rockwell** instructions. 

The questions are:

1. Is the 65C816 going to become standard equipment at some point? This seems like a question for David and Kevin, and we really need this answered before any other decisions can be made.
  a. If the 65C816 is made standard for Gen-2, then we need to gracefully deprecate the 65C02 instructions. 
  b. If it is *not* made standard, then this whole discussion can be dismissed.

Some thoughts on handling the deprecation: 
1. Disable the opcodes and crash the emu when an x7 or xF opcode is executed. This will help prevent people from including those instructions in new code, since it will fail in the emulator.
2. Warn the user via the console: `Warning: executed deprecated opcode xx`
3. Add a command line switch to either override or enable the above actions.
4. If 65C816 emulation is added to the emulator, should we consider flagging these opcodes in the 816 emulation, to help track down potential bugs in legacy code?

My thoughts are:
1. Never disable the instructions.
2. Flag the opcode use in 65C02 mode by writing a message to the console.
3. Add a "-testc02" flag that halts the CPU when a Rockwell instruction is executed.

The -testc02 flag should work the same, whether 65C02 or 65C816 emulation is active, helping developers look for this issue no matter which CPU they are running.

**Comment by mooinglemur** [comment]
This is mostly handled in the `65c816` branch.  Under `-c02`, it will emit a single warning (with memory address) at the first occurrence of executing a Rockwell instruction, but that warning can be suppressed with `-rockwell`.  Obviously under `-c816` those opcodes belong to different instructions, so the warning logic will not apply.

**Comment by mooinglemur** [comment]
I'm hoping we'll be able to merge the `65c816` branch to `master` within weeks.
