### ISSUE TITLE
Compile failure under alpine linux

### ISSUE THREAD

**Issue by jholt0147** [X16Community/x16-emulator#220]
Emulator currently fails to compile on postmarket OS and Alpine Linux due to PATH_MAX being undefined in src/video.c . This I believe is because of the use of mus c library.  I'm not programmer however I was able to get the binary to compile by setting a value of 4096.  Hardware specifications are mt8183 arm CPU aarch64 postmarketos

**Comment by mooinglemur** [comment]
I think we might have just been missing an include.  Was the compile error in ieee.c?  If so, the commit I'm about to merge should fix it.
