### ISSUE TITLE
Can no longer supply BASIC code via command output

### ISSUE THREAD

**Issue by markjreed** [X16Community/x16-emulator#233]
Due to [a change in SDL2](https://github.com/sezero/SDL/commit/c9c7d58a5b138a034a0b68613e3ce0e7c8172bf2), I can no longer supply BASIC code to run via `-bas <(echo 'basic code here')`, which broke my automated testing.  [SDL2 issue here](https://github.com/libsdl-org/SDL/issues/9174).

Maybe x16emu could add a way to run code supplied as a string instead of a file to mitigate that dependency?

**Comment by mooinglemur** [comment]
@markjreed are you good with the upstream fix?

**Comment by markjreed** [comment]
Upstream fix works. Thanks!
