### ISSUE TITLE
Writing to sectors outside of the SD card image enlarges the image

### ISSUE THREAD

**Issue by Fulgen301** [X16Community/x16-emulator#4]
In

https://github.com/X16Community/x16-emulator/blob/96961d8c5dd40ada31e8ce50f1a4145b97cad861/src/sdcard.c#L258-L259

, the emulator passes the LBA address to `SDL_RWseek` and then writes to that position. If the new position is past the image file's end, this writing enlarges the file. Thus, an application running inside the emulator can enlarge the SD card - a write to LBA address `UINT_MAX` will result in a 4 GiB large image (only 4 GiB due to an overflow bug).

Before:
```
$ stat ../sdcard.img  | grep Size
  Size: 2048            Blocks: 8          IO Block: 4096   regular file
```

After:
```
$ stat ../sdcard.img  | grep Size
  Size: 4294967296      Blocks: 16         IO Block: 4096   regular file
```

**Comment by mooinglemur** [comment]
Can you please try your test case against https://github.com/mooinglemur/x16-emulator/actions/runs/4189979882
or from the branch https://github.com/mooinglemur/x16-emulator/tree/2023-02-15-sdcardsize

This should solve #5 also

**Comment by Fulgen301** [comment]
Works, the SD card size isn't increased anymore. However, the write is still reported as a success (`sdcard_write_sector` returns with C=1).

**Comment by mooinglemur** [comment]
Aha, I'll see if I can fix that.  Can you test the `read` case? I'm hoping that properly returns an error condition.

**Comment by Fulgen301** [comment]
Using https://github.com/mooinglemur/x16-emulator/actions/runs/4198161437, the `read` case returns an error, but writing still succeeds.

I'm testing with reading / writing LBA `UINT_MAX` with a 1024 sector image.
