### ISSUE TITLE
Emulator crashes when opening a file first thing

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-emulator#50]
**Description**

When opening a sequential file immediately after launching the emulator, I can crash the emulator.

**Reproduction Steps**
Start the emulator. 
Without typing anything else, enter the following program line:
```
10 OPEN 8,8,8,"SEQ.SEQ,S,W"
RUN
```
The emulator closes with no obvious error code or other information.

If I so much as LIST the program or even just press CR one more time, the failure does not seem to happen. Also, after trying this several times, the error seems to have gone away. So this problem seems to depend on a specific, transient situation. 

Since this error is so hard to reproduce, I'd probably qualify this as low-impact, low-priority.

**Comment by FlightControl-User** [comment]
Same here ... I get a blank screen ... Some files load, but some files don't.
It seems to only happen when accessing the files directly from the host.
When accessing the files form an sdcard it seems to run fine.

Pls try to confirm this behaviour too.

**Comment by tomxp411** [comment]
So far, I can't reproduce this error. Crashes on file I/O are kind of random, and other than this specific test I haven't found any other reproducible failures. Even this one went away as I played with it that night.

**Comment by mooinglemur** [comment]
Prior to #81 the `channels` struct didn't get properly initialized before it got checked. I feel like this is a better candidate for a fix for this issue than anything prior, and I have gone through the code to try to find any possible other reason for I/O to trigger a crash and haven't found one.  If you encounter any more semi-reproducible crash scenarios, please open another issue.
