### ISSUE TITLE
Host file system does not handle channel 15 communication checks well?

### ISSUE THREAD

**Issue by FlightControl-User** [X16Community/x16-emulator#56]
I have a loop that opens channel 15, checks for the error code on the drive and returns the error if any.
The error text is retrieved by iterating each character fetch using CHRIN until READST returns $40, which is EOF.

![image](https://user-images.githubusercontent.com/13690775/226175515-2328522d-2f0f-42fc-bc07-6bf6fe9db9fd.png)

This works well with -sdcard flag enabled. I've put a breakpoint and have debugged the code till the last character read from CHRIN of the error message. The debug shows the error message location read, and the processor is right after the last READST call, which is behind address $1685. The error text return is 00, OK,00,00 which is ok.

![image](https://user-images.githubusercontent.com/13690775/226175641-892044fd-7fe4-47fc-aa39-49575f774416.png)

The accumulator contains $40 which is the expected behaviour I guess ... Here the loop will stop and the parsed error code is returned.

However, when executing exactly the same logic, without the -sdcard option and running this directly from the host, we get this situation:

![image](https://user-images.githubusercontent.com/13690775/226175782-f897301e-8b86-44ab-8c42-a28e504a9d9f.png)

Here READST does not return $40 at the end of the text. It returns just $00. 
And the loop will continue forever, overwriting unwanted memory ...

Sven

**Comment by FlightControl-User** [comment]
Strangely, when i do this through BASIC it seems to work fine ...

![image](https://user-images.githubusercontent.com/13690775/226176041-db16aece-12bd-42eb-aa4c-891cb7f263d9.png)

But loading FILE2.BIN from the host seems to hang the system also ... loaded into $0801 till $09A3.

![image](https://user-images.githubusercontent.com/13690775/226176104-2423c03f-60f7-478c-b5cb-c4ffc110f1ae.png)

**Comment by mooinglemur** [comment]
Thanks for the report.  This has already been fixed by #48
