### ISSUE TITLE
SMC Read on a unhanded 'offset' returns an incorrect value

### ISSUE THREAD

**Issue by Yazwh0** [X16Community/x16-emulator#57]
If the offset isn't 0x07 (keyboard) or 0x21 (mouse) the emulator returns a 0xff, while the SMC code appears to return 0x00.

Emulator:
![image](https://user-images.githubusercontent.com/90315107/226189656-1dbb8a06-cf80-4c4f-8a6c-d275ec00485e.png)

SMC:
![image](https://user-images.githubusercontent.com/90315107/226189670-e189cde2-8321-4f0f-ae7e-e014b9e16c6a.png)

**Comment by mooinglemur** [comment]
The SMC ignores unsupported offsets.  Tested on hardware, you do get 0xff when reading from other offsets.  The `Wire.write(0)` with your arrow is actually inside the handler for the 0x21 offset, and not actually in the same place as the default in the emu.
